FROM node:10-alpine3.9 as build-stage

COPY ./frontend-example-docker /home
WORKDIR /home

RUN npm install && \
 npm run build 
 

FROM nginx

RUN adduser --disabled-password app && \
 chown -R app /home

COPY --from=build-stage /home/dist /usr/share/nginx/html
USER app
EXPOSE 80 

