version: '3.5' 

services: 
    backend: 
      image: backend-exer2.3 
      environment: 
       - REDIS=my-redis
       - REDIS_PORT=6379
       - FRONT_URL=http://192.168.11.110:5000
      ports:
       - 8000:8000

    frontend:
       image: frontend-exer2.3
       ports:
          - 5000:5000
       environment:
          - API_URL=http://192.168.11.110:8000
    my-redis: 
      image: redis:latest 
      container_name: my-redis
