FROM ruby:2.6.0


COPY rails-example-project /home
WORKDIR /home
RUN bundle install
RUN apt update && apt install nodejs -y
RUN rails db:migrate
RUN rake assets:precompile
EXPOSE 3000

ENTRYPOINT ["rails", "s"]
